apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: w8cs1mybq-go 
  janus-idp.io/tekton: w8cs1mybq-go
  backstage.io/kubernetes-id: w8cs1mybq-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: w8cs1mybq-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml