apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: w8cs1mybq-go
  janus-idp.io/tekton: w8cs1mybq-go
  backstage.io/kubernetes-id: w8cs1mybq-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: w8cs1mybq-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
